### ISSUE TITLE
Sharing the official repo

### ISSUE THREAD

**Issue by mohmdelsayed** [lucidrains/streaming-deep-rl#1]
Hi @lucidrains!

This is Mohamed, one of the authors of the streaming deep RL paper. I came across your repo, and I see that you're working on reproducing our Stream Q(λ) algorithm. I appreciate your interest! I just wanted to share with you that we released our code a few days ago in case you want to use it as a reference. I'm happy that you're trying to integrate Stream Q(λ) into more complex setups. Please let me know if you have any questions. Thanks!

https://github.com/mohmdelsayed/streaming-drl

**Comment by lucidrains** [comment]
oh hey Mohamed! this is a very cool paper! 🙏

I had no idea you open sourced it, must have missed the link in the paper. I will add a link to your official repo, but will bring it to completion here to see if I can modularize some logic for use in q-transformers

Thank you!

**Comment by lucidrains** [comment]
@mohmdelsayed have you read the [SimBa](https://arxiv.org/abs/2410.09754) paper and seen their running statistics normalization?

**Comment by mohmdelsayed** [comment]
I haven't read this paper yet; it's on my list. Thanks for sharing! They compute the variance incrementally using the standard incremental form. In our paper, we use [Welford's algorithm](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Welford's_online_algorithm), which is considered to be more numerically stable when computing the running variance than the standard method.

**Comment by lucidrains** [comment]
@mohmdelsayed noted! two separate groups converging on a similar finding is what I like to see 🙏
